### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by E3V3A** [theawsomeavr/Attiny85_Playtune_master#1]
Compiling `marble_machine_wintergatan_without_library.ino`, results in: 
```
marble_machine_wintergatan_without_library:526:23: error: invalid conversion from 'const byte* {aka const unsigned char*}' to 'byte* {aka unsigned char*}' [-fpermissive]

   tune_playscore(score); 

                       ^

marble_machine_wintergatan_without_library:141:6: error: initializing argument 1 of 'void tune_playscore(byte*)' [-fpermissive]

 void tune_playscore (byte *score) {

      ^

exit status 1
invalid conversion from 'const byte* {aka const unsigned char*}' to 'byte* {aka unsigned char*}' [-fpermissive]
```

Any ideas how to resolve this?

**Comment by theawsomeavr** [comment]
Sorry for being extremely late, I didn´t notice that mistake.
You only need to change  void tune_playscore (byte *score) to void tune_playscore (const byte *score).
Also try to use the other example not this one

**Comment by theawsomeavr** [comment]
you also need to change the score_start and score_cursor to a volatile const byte.
I have now updated this repo so it is fixed
